is_addon_installed:
  description: Log if addon is installed.
  fields:
    slug:
      description: The addon slug as defined in the add-on config.json.
      example: ssh
    repository:
      description: The addon repository id.
      example: core
is_addon_started:
  description: Log if addon is started.
  fields:
    slug:
      description: The addon slug as defined in the add-on config.json.
      example: ssh
    repository:
      description: The addon repository id.
      example: core
install_addon:
  description: Install addon.
  fields:
    slug:
      description: The addon slug as defined in the add-on config.json.
      example: check_config
    repository:
      description: The addon repository id.
      example: core
uninstall_addon:
  description: Uninstall addon.
  fields:
    slug:
      description: The addon slug as defined in the add-on config.json.
      example: check_config
    repository:
      description: The addon repository id.
      example: core
start_addon:
  description: Start addon.
  fields:
    slug:
      description: The addon slug as defined in the add-on config.json.
      example: configurator
    repository:
      description: The addon repository id.
      example: core
